name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Download the dependencies
      run: go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.35
        only-new-issues: true
        
    - name: Build
      run: go build -v ./pkg/...

    - name: Install go-acc
      run: go get github.com/ory/go-acc
    - name: Run tests
      run: go-acc ./pkg/...
    - name: Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        files: coverage.txt
